name: Jenkins

on:
  push:
    paths:
      - .github/workflows/jenkins.yml
      - compose.yaml
      - Dockerfile
      - jenkins_home/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - run: docker compose version
      - uses: actions/checkout@v3
      - run: chown -R 1000:1000 jenkins_home/
      - run: docker compose up -d --wait jenkins
      - run: ls -la jenkins_home/
      - run: |
          OWNER=$(id --user):$(id --group)
          echo $OWNER
      - run: docker compose run --rm jenkins-plain id --user
      - run: docker compose run --rm jenkins-plain id --group
      - run: docker compose run --rm -u root jenkins --version
      - run: curl http://localhost:8080/
      - run: curl -X POST http://localhost:8080/job/job-1/build
