name: Jenkins

on:
  push:
    paths:
      - .github/workflows/jenkins.yml
      - compose.yaml
      - Dockerfile
      - jenkins_home/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - run: docker compose version
      - uses: actions/checkout@v3
      - run: sudo chown -R 1000:1000 jenkins_home/
      - run: docker compose up -d --wait jenkins
      - run: ls -la jenkins_home/
      - run: |
          OWNER=$(id --user):$(id --group)
          echo $OWNER
      - run: docker compose run --rm jenkins --version
      - run: curl http://localhost:8080/
      - run: curl -s http://localhost:8080/crumbIssuer/api/json
      - run: |
          crumb=$(curl -s -c cookie http://localhost:8080/crumbIssuer/api/json)
          echo $crumb
          echo "::set-output name=json::${crumb}"
        id: crumb
      - run: curl -X POST -H "${crumb_header}" -b cookie http://localhost:8080/job/job-1/build
        env:
          crumb_header: '${{ fromJSON(steps.crumb.outputs.json).crumbRequestField }}:${{ fromJSON(steps.crumb.outputs.json).crumb }}'
      - run: |
          set -x
          sleep 10s
          start=0
          while [ $(curl -sS -H "${crumb_header}" -b cookie http://localhost:8080/job/job-1/1/api/json | jq '.building') = "true" ]; do
            text=$(curl -sS -H "${crumb_header}" -b cookie "http://localhost:8080/job/job-1/1/logText/progressiveText?start=${start}")
            echo $text
            echo "text length: ${#text}"
            start=$((start + ${#text}))
            echo "start: ${start}"
            
            sleep 5s
          done
        env:
          crumb_header: '${{ fromJSON(steps.crumb.outputs.json).crumbRequestField }}:${{ fromJSON(steps.crumb.outputs.json).crumb }}'
