name: Jenkins

on:
  push:
    paths:
      - .github/workflows/jenkins.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - run: docker compose up -d --wait jenkins
      - run: curl http://localhost:8080/
      - run: curl -X POST http://localhost:8080/job/job-1/build
