name: Jenkins

on:
  push:
    paths:
      - .github/workflows/jenkins.yml
      - compose.yaml
      - Dockerfile
      - jenkins_home/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - run: docker compose version
      - uses: actions/checkout@v3
      - run: docker compose up -d jenkins
      - run: ls -la
      - run: ls -la jenkins_home/
      - run: sleep 30s
      - run: docker compose exec jenkins ls -la /var/jenkins_home/
      - run: docker compose run --rm jenkins --version
      - name: Wait for starting
        run: |
          set -x
          until [ "$(docker inspect --format='{{.State.Health.Status}}' $(docker compose ps -q jenkins))" = 'healthy' ]; do
            docker compose exec jenkins ls -la /var/jenkins_home/plugins/
            sleep 5s
          done
      - run: curl http://localhost:8080/
      - run: curl -X POST http://localhost:8080/job/job-1/build
