name: Jenkins

on:
  push:
    paths:
      - .github/workflows/jenkins.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
      - run: docker-compose version
      - uses: actions/checkout@v3
      - run: docker-compose up -d jenkins-plain
      - name: Wait for starting
        run: |
          set -x
          until [ "$(docker inspect --format='{{.State.Health.Status}}' $(docker-compose ps -q jenkins-plain))" = 'healthy' ]; do
            sleep 5s
          done
      - run: curl http://localhost:8080/
      - run: curl -X POST http://localhost:8080/job/job-1/build
