name: Jenkins

on:
  push:
    paths:
      - .github/workflows/jenkins.yml
      - compose.yaml
      - Dockerfile
      - jenkins_home/**
      - Jenkinsfile
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      JENKINS_HOME: ./jenkins_home

    steps:
      - run: docker compose version
      - uses: actions/checkout@v3
      - run: sudo chown -R 1000:1000 $JENKINS_HOME
      - run: docker compose up -d --wait jenkins
      - run: ls -la $JENKINS_HOME
      - run: |
          OWNER=$(id --user):$(id --group)
          echo $OWNER
      - run: docker compose run --rm jenkins --version
      - run: curl http://localhost:8080/
      - run: curl -s http://localhost:8080/crumbIssuer/api/json
      - run: |
          crumb=$(curl -s -c cookie http://localhost:8080/crumbIssuer/api/json)
          echo $crumb
          echo "CRUMB_HEADER=$(echo $crumb | jq -r '.crumbRequestField'): $(echo $crumb | jq -r '.crumb')" >> $GITHUB_ENV
        id: crumb
      # - run: curl -X POST -H "${CRUMB_HEADER}" -b cookie http://localhost:8080/job/job-1/build
      # https://stackoverflow.com/questions/51638867/how-to-get-the-right-build-number-for-a-build-triggered-in-jenkins-by-remote-api
      - run: curl -X POST -H "${CRUMB_HEADER}" -b cookie http://localhost:8080/job/job-1/buildWithParameters?pr_number=177 --head
      - run: |
          set -x
          sleep 10s
          start=0
          while [ $(curl -sS -H "${CRUMB_HEADER}" -b cookie http://localhost:8080/job/job-1/1/api/json | jq '.building') = "true" ]; do
            text=$(curl -sS -H "${CRUMB_HEADER}" -b cookie "http://localhost:8080/job/job-1/1/logText/progressiveText?start=${start}")
            echo $text
            echo "text length: ${#text}"
            start=$((start + ${#text}))
            echo "start: ${start}"
            
            sleep 5s
          done
      - run: curl -sS -H "${CRUMB_HEADER}" -b cookie http://localhost:8080/job/job-1/1/logText/progressiveText?start=0
      - run: |
          set -x
          result=$(curl -sS -H "${CRUMB_HEADER}" -b cookie http://localhost:8080/job/job-1/1/api/json | jq -r '.result')
          test "$result" = "SUCCESS"
